In [1]:
from sklearn.datasets import fetch_openml
import numpy as np

mnist = fetch_openml('mnist_784', version=1)

mnist_X, mnist_y = mnist['data'], mnist['target'].astype(np.uint8)

partition = 60000
mnist_X_train, mnist_X_test, mnist_y_train, mnist_y_test = mnist_X[:partition], mnist_X[partition:], mnist_y[:partition], mnist_y[partition:]

In [3]:
from sklearn.linear_model import SGDClassifier

is_5_mnist_y_train = (mnist_y_train == 5)

sgd_classifier = SGDClassifier(random_state=42)
sgd_classifier.fit(mnist_X_train, is_5_mnist_y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [5]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_classifier, mnist_X_train, is_5_mnist_y_train, cv=3, scoring='accuracy')

array([0.95035, 0.96035, 0.9604 ])

In [7]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_classifier, mnist_X_train, is_5_mnist_y_train, cv=3)
y_train_pred

array([ True, False, False, ...,  True, False, False])

In [9]:
from sklearn.metrics import confusion_matrix

confusion_matrix(is_5_mnist_y_train, y_train_pred)

array([[53892,   687],
       [ 1891,  3530]])

In [11]:
from sklearn.metrics import precision_score

precision_score(is_5_mnist_y_train, y_train_pred)

0.8370879772350012

In [12]:
from sklearn.metrics import recall_score

recall_score(is_5_mnist_y_train, y_train_pred)

0.6511713705958311

In [13]:
from sklearn.metrics import f1_score

f1_score(is_5_mnist_y_train, y_train_pred)

0.7325171197343846