In [1]:
from sklearn.datasets import fetch_openml
import numpy as np

mnist = fetch_openml('mnist_784', version=1)

X, y = mnist['data'], mnist['target'].astype(np.uint8)

partition = 60000
X_train, X_test, y_train, y_test = X[:partition], X[partition:], y[:partition], y[partition:]

In [3]:
from sklearn.linear_model import SGDClassifier

y_5_train = (y_train == 5)

sgd_classifier = SGDClassifier(random_state=42)
sgd_classifier.fit(X_train, y_5_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=42, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [4]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_classifier, X_train, y_5_train, cv=3, scoring='accuracy')

array([0.95035, 0.96035, 0.9604 ])

In [6]:
from sklearn.model_selection import cross_val_predict

y_5_hat_train = cross_val_predict(sgd_classifier, X_train, y_5_train, cv=3)
y_5_hat_train

array([ True, False, False, ...,  True, False, False])

In [7]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_5_train, y_5_hat_train)

array([[53892,   687],
       [ 1891,  3530]])

In [8]:
from sklearn.metrics import precision_score

precision_score(y_5_train, y_5_hat_train)

0.8370879772350012

In [9]:
from sklearn.metrics import recall_score

recall_score(y_5_train, y_5_hat_train)

0.6511713705958311

In [10]:
from sklearn.metrics import f1_score

f1_score(y_5_train, y_5_hat_train)

0.7325171197343846